### PR TITLE
REFACTOR: Scripts.js 11/01

### PR DESCRIPTION
**Pull request by sam-rice**
### Refactored Scripts.js according to SRP

- `initPage()`
  - changed function name `startPage()` to `initPage()` per standard naming convention
  - added `initRecipeRepository()` and `initUser()` helper functions and their invocations within `initPage()` per Cass' notes
  - same as above for `displayWelcomeMessage()`

- added `getRandomIndex()` helper function for use in initializing featured recipe and for possible use with future functionality
- added function-scoped boolean variables to several event handlers that make the complex chains of conditional statements more readable (see lines 97, 98, 116, 129, etc.). This was a trick that I saw Tim's friend suggested. Some notes on this:
  - some of the more complex handlers wouldn't allow me to pre-define certain truthy/falsy expressions, since they would evaluate to `undefined` (for example, if the `event.target` has no `.src` because the user clicks on an element without a `.src` attribute) and throw an error at the top of the function. I tried to be consistent with using these boolean variables whenever possible.
  - Although it takes more lines of code to do the same thing, I think it makes the code more readable. That being said, if we decide as a team that this isn't an approach we like, I'm happy to revert it back, and it wouldn't take long.
- added `removeTileFromDisplay()`, which solves the previous issue of having the filter reset when un-saving a recipe in "My Recipes" view. Now, the tile is targeted and removed without refreshing the "My Recipes" view (previously done with `displayCurrentMode()`), allowing us to stay tag-filtered.
- removed `displayCurrentMode()`, since the only functionality it was handling was the functionality explained above.
- added `enableFilterClearButton()` and `disableFilterClearButton()` helper functions to DRY up filtering event handlers.
- added `makeViewButtonActive()` to DRY up DOM functions.

### Styles.css

- removed styling which removed focus outline of close button in modal

### Where to Begin with Review

Please double-check all functionality/user paths have been preserved

### CODE REVIEW

**Comment by Speekins** [comment]
This looks good, Sam. I especially like that you DRYed up the code by reserving specific functionality to new helper functions. 

- `removeTileFromDisplay` was a great idea in lieu of `displayCurrentMode`. This is kind of a big change so it would probably be a good idea to discuss with the team.
- Can we combine the functions `enableFilterClearButton` and `disableFilterClearButton`? They are excellent functions and very descriptive, but I think one function could handle all the logic.
- Creating the variables that hold boolean values was a great idea. Thank you for doing that. Maybe we can figure out some ways to implement this throughout the program more.
- `initUser` and `initRecipeRepository` are each only doing one thing and I'm wondering if we need them. I understanding meeting the SRP and DRYing up the code, but can these class instantiations simply be done within `initPage`?
- I'm getting a bug that I'm not sure if its pre-existent of this branch—the modal does not open in the My Recipes view. I created a bug ticket as I'm sure we can tackle that easily.
- My only other feedback is that this PR was pretty bulky—a lot to review. If possible it would help to keep changes compartmentalized. We've all been doing the same and I understand it's annoying to submit multiple PR's for seemingly small changes. Another subject to discuss with the team.

**Comment by sam-rice** [comment]
Hey, so in response to each of your bullets: 
- I agree, we should go over this one as a team—maybe at standups today, if everyone's okay getting into code for a minute.
- Also agree. I had this thought while re-reading my PR this morning. Maybe we could just have `enableFilterClearButton()` which takes true/false as an arg and just toggles between the two states of the button?
- Sounds good re boolean variables
- I sort of agree here. I think it was a specific thing Cass mentioned doing—although she didn't explicitly say to make helper functions initializing those instantiations. Maybe we can discuss as a group too.
- I'm going to check on the modal bug. It probably was new to my branch here, thanks for catching that.
- Yeah, this was a big one. I'll keep that in mind in the future. 

I think I should make a few changes to this branch after standups before we merge this. Especially if there's an issue with the modal. Can we hold off?

**Comment by Speekins** [comment]
Cool. Sounds good. Thank you for taking the time to refactor some before we merge.
And it appears the modal bug is new. I checked main and I can still open modals within the My Recipes view.

**Comment by sam-rice** [comment]
## The discussed changes have been made (see below) and this branch is ready for a new review.

- BUG FIX: Modal not displaying from "My Recipes" view 
- `enableFilterClearButton()` and `disableFilterClearButton()` have been combined into `enableFilterClearButton(boolean)` as discussed in comment thread

**Comment by zacwalters4** [comment]
I'm impressed by Spencer's keen eye and also Sam's haste fixing the issues that were brought up. Looks great guys!

**Pull request merged**
